In [205]:
import pandas as pd
import matplotlib.pyplot as plt

In [206]:
df = pd.read_csv ('Cleaned_data.csv')

In [207]:
#df.date = pd.to_datetime(df.date,format="%d/%m/%Y")
#df.set_index('date', inplace=True)
#df.head()

######################################## DAILY PRECENT CHANGE ######################################

In [208]:
df['Pct_Change'] = df.groupby("Name")['close'].pct_change() * 100
df.head()

         date   open   high    low  close    volume Name  Pct_Change
0  2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL         NaN
1  2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL   -1.966102
2  2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL   -1.313970
3  2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL    2.733006
4  2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL   -4.570259

#################################### ABS PCT CHANGE ##############################

In [209]:
# יצירת פיצ'ר של עוצמת תנועה יומית (בלי קשר לכיוון)
df['Abs_Pct_Change'] = df['Pct_Change'].abs()
df.head()

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259

############################## Gap PCT ##################################################

In [210]:
# אנחנו מבקשים מפייתון לעשות את ה-shift בנפרד לכל מניה
df['gap'] = abs((df['open'] - df['close'].groupby(df['Name']).shift(1)) / df['close'].groupby(df['Name']).shift(1)) * 100
df.head()

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN,NaN
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102,0.949153
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970,0.069156
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006,0.210231
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259,1.909959

########################################חישוב הזנב העליון (תמיד חיובי) ########################################

In [211]:
# 1. חישוב הזנב העליון (תמיד חיובי)
df['Upper_Shadow'] = df['high'] - df[['open', 'close']].max(axis=1)

df.head(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN,NaN,0.05
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102,0.949153,0.12
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970,0.069156,0.06
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006,0.210231,0.28
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259,1.909959,0.02
5,2013-02-15,13.93,14.61,13.93,14.50,15628000,AAL,3.645461,3.645461,0.428878,0.11
6,2013-02-19,14.33,14.56,14.08,14.26,11354400,AAL,-1.655172,1.655172,1.172414,0.23
7,2013-02-20,14.17,14.26,13.15,13.33,14725200,AAL,-6.521739,6.521739,0.631136,0.09
8,2013-02-21,13.62,13.95,12.90,13.37,11922100,AAL,0.300075,0.300075,2.175544,0.33
9,2013-02-22,13.57,13.60,13.21,13.57,6071400,AAL,1.495886,1.495886,1.495886,0.03

####################################### חישוב הזנב התחתון (תמיד חיובי)########################################

In [212]:
# 2. חישוב הזנב התחתון (תמיד חיובי)
df['Lower_Shadow'] = df[['open', 'close']].min(axis=1) - df['low']
df.head(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow,Lower_Shadow
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN,NaN,0.05,0.12
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102,0.949153,0.12,0.20
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970,0.069156,0.06,0.17
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006,0.210231,0.28,0.05
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259,1.909959,0.02,0.83
5,2013-02-15,13.93,14.61,13.93,14.50,15628000,AAL,3.645461,3.645461,0.428878,0.11,0.00
6,2013-02-19,14.33,14.56,14.08,14.26,11354400,AAL,-1.655172,1.655172,1.172414,0.23,0.18
7,2013-02-20,14.17,14.26,13.15,13.33,14725200,AAL,-6.521739,6.521739,0.631136,0.09,0.18
8,2013-02-21,13.62,13.95,12.90,13.37,11922100,AAL,0.300075,0.300075,2.175544,0.33,0.47
9,2013-02-22,13.57,13.60,13.21,13.57,6071400,AAL,1.495886,1.495886,1.495886,0.03,0.36

########################## סך הכל זנבות בדולרים #######################

In [213]:
# 3. סך הכל זנבות בדולרים
df['Total_Shadow_USD'] = df['Upper_Shadow'] + df['Lower_Shadow']
df.head(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow,Lower_Shadow,Total_Shadow_USD
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN,NaN,0.05,0.12,0.17
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102,0.949153,0.12,0.20,0.32
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970,0.069156,0.06,0.17,0.23
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006,0.210231,0.28,0.05,0.33
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259,1.909959,0.02,0.83,0.85
5,2013-02-15,13.93,14.61,13.93,14.50,15628000,AAL,3.645461,3.645461,0.428878,0.11,0.00,0.11
6,2013-02-19,14.33,14.56,14.08,14.26,11354400,AAL,-1.655172,1.655172,1.172414,0.23,0.18,0.41
7,2013-02-20,14.17,14.26,13.15,13.33,14725200,AAL,-6.521739,6.521739,0.631136,0.09,0.18,0.27
8,2013-02-21,13.62,13.95,12.90,13.37,11922100,AAL,0.300075,0.300075,2.175544,0.33,0.47,0.80
9,2013-02-22,13.57,13.60,13.21,13.57,6071400,AAL,1.495886,1.495886,1.495886,0.03,0.36,0.39

##################################### סך הכל זנבות כאחוז מהטווח היומי ################################

In [214]:
# 4. סך הכל זנבות כאחוז מהטווח היומי (זה הפיצ'ר הכי חזק לקלסטרינג!)
df['Shadow_to_Range'] = df['Total_Shadow_USD'] / (df['high'] - df['low'])
df.head(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow,Lower_Shadow,Total_Shadow_USD,Shadow_to_Range
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN,NaN,0.05,0.12,0.17,0.346939
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102,0.949153,0.12,0.20,0.32,0.426667
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970,0.069156,0.06,0.17,0.23,0.560976
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006,0.210231,0.28,0.05,0.33,0.478261
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259,1.909959,0.02,0.83,0.85,0.472222
5,2013-02-15,13.93,14.61,13.93,14.50,15628000,AAL,3.645461,3.645461,0.428878,0.11,0.00,0.11,0.161765
6,2013-02-19,14.33,14.56,14.08,14.26,11354400,AAL,-1.655172,1.655172,1.172414,0.23,0.18,0.41,0.854167
7,2013-02-20,14.17,14.26,13.15,13.33,14725200,AAL,-6.521739,6.521739,0.631136,0.09,0.18,0.27,0.243243
8,2013-02-21,13.62,13.95,12.90,13.37,11922100,AAL,0.300075,0.300075,2.175544,0.33,0.47,0.80,0.761905
9,2013-02-22,13.57,13.60,13.21,13.57,6071400,AAL,1.495886,1.495886,1.495886,0.03,0.36,0.39,1.000000

In [215]:
##################### תנודתיות תוך-יומית (High-Low Range) #####################

df['Daily_Range'] = ((df['high'] - df['low']) / df['close']) * 100

################################ התשואה היומית של המניה באחוזים ###############################

In [216]:
# מחושב בדרך כלל ברמה השבועית או החודשית, אבל כאן נכין את הבסיס היומי
df['Daily_Return'] = df.groupby('Name')['close'].pct_change()
df.head(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow,Lower_Shadow,Total_Shadow_USD,Shadow_to_Range,Daily_Return
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN,NaN,0.05,0.12,0.17,0.346939,NaN
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102,0.949153,0.12,0.20,0.32,0.426667,-0.019661
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970,0.069156,0.06,0.17,0.23,0.560976,-0.013140
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006,0.210231,0.28,0.05,0.33,0.478261,0.027330
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259,1.909959,0.02,0.83,0.85,0.472222,-0.045703
5,2013-02-15,13.93,14.61,13.93,14.50,15628000,AAL,3.645461,3.645461,0.428878,0.11,0.00,0.11,0.161765,0.036455
6,2013-02-19,14.33,14.56,14.08,14.26,11354400,AAL,-1.655172,1.655172,1.172414,0.23,0.18,0.41,0.854167,-0.016552
7,2013-02-20,14.17,14.26,13.15,13.33,14725200,AAL,-6.521739,6.521739,0.631136,0.09,0.18,0.27,0.243243,-0.065217
8,2013-02-21,13.62,13.95,12.90,13.37,11922100,AAL,0.300075,0.300075,2.175544,0.33,0.47,0.80,0.761905,0.003001
9,2013-02-22,13.57,13.60,13.21,13.57,6071400,AAL,1.495886,1.495886,1.495886,0.03,0.36,0.39,1.000000,0.014959

############################## STD ###############################

In [217]:
df['Rolling_Volatility_10D'] = (
    df.groupby('Name')['Daily_Return']
    .rolling(window=10)
    .std()
    .reset_index(level=0, drop=True)
)
df.tail(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow,Lower_Shadow,Total_Shadow_USD,Shadow_to_Range,Daily_Return,Rolling_Volatility_10D
589202,2018-01-25,78.47,79.38,78.345,79.25,2327262,ZTS,1.174518,1.174518,0.178731,0.13,0.125,0.255,0.246377,0.011745,0.006500
589203,2018-01-26,79.49,80.13,79.380,80.09,2532808,ZTS,1.059937,1.059937,0.302839,0.04,0.110,0.150,0.200000,0.010599,0.006567
589204,2018-01-29,79.81,79.95,79.110,79.18,2662383,ZTS,-1.136222,1.136222,0.349607,0.14,0.070,0.210,0.250000,-0.011362,0.008626
589205,2018-01-30,78.44,78.69,77.910,78.35,3808707,ZTS,-1.048245,1.048245,0.934579,0.25,0.440,0.690,0.884615,-0.010482,0.009908
589206,2018-01-31,78.49,78.77,76.540,76.73,4136360,ZTS,-2.067645,2.067645,0.178685,0.28,0.190,0.470,0.210762,-0.020676,0.011465
589207,2018-02-01,76.84,78.27,76.690,77.82,2982259,ZTS,1.420566,1.420566,0.143360,0.45,0.150,0.600,0.379747,0.014206,0.012074
589208,2018-02-02,77.53,78.12,76.730,76.78,2595187,ZTS,-1.336417,1.336417,0.372655,0.59,0.050,0.640,0.460432,-0.013364,0.012976
589209,2018-02-05,76.64,76.92,73.180,73.83,2962031,ZTS,-3.842146,3.842146,0.182339,0.28,0.650,0.930,0.248663,-0.038421,0.017151
589210,2018-02-06,72.74,74.56,72.130,73.27,4924323,ZTS,-0.758499,0.758499,1.476365,1.29,0.610,1.900,0.781893,-0.007585,0.017031
589211,2018-02-07,72.70,75.00,72.690,73.86,4534912,ZTS,0.805241,0.805241,0.777945,1.14,0.010,1.150,0.497835,0.008052,0.016890

################################ שינוי בנפח המסחר (Volume Change) ############################

In [218]:
df['Volume_Pct_Change'] = df.groupby('Name')['volume'].pct_change() * 100
df.head(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow,Lower_Shadow,Total_Shadow_USD,Shadow_to_Range,Daily_Return,Rolling_Volatility_10D,Volume_Pct_Change
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN,NaN,0.05,0.12,0.17,0.346939,NaN,NaN,NaN
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102,0.949153,0.12,0.20,0.32,0.426667,-0.019661,NaN,5.643770
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970,0.069156,0.06,0.17,0.23,0.560976,-0.013140,NaN,-8.511596
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006,0.210231,0.28,0.05,0.33,0.478261,0.027330,NaN,26.255230
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259,1.909959,0.02,0.83,0.85,0.472222,-0.045703,NaN,210.735416
5,2013-02-15,13.93,14.61,13.93,14.50,15628000,AAL,3.645461,3.645461,0.428878,0.11,0.00,0.11,0.161765,0.036455,NaN,-50.978516
6,2013-02-19,14.33,14.56,14.08,14.26,11354400,AAL,-1.655172,1.655172,1.172414,0.23,0.18,0.41,0.854167,-0.016552,NaN,-27.345790
7,2013-02-20,14.17,14.26,13.15,13.33,14725200,AAL,-6.521739,6.521739,0.631136,0.09,0.18,0.27,0.243243,-0.065217,NaN,29.687170
8,2013-02-21,13.62,13.95,12.90,13.37,11922100,AAL,0.300075,0.300075,2.175544,0.33,0.47,0.80,0.761905,0.003001,NaN,-19.036074
9,2013-02-22,13.57,13.60,13.21,13.57,6071400,AAL,1.495886,1.495886,1.495886,0.03,0.36,0.39,1.000000,0.014959,NaN,-49.074408

######################################### VOLUME STD ###################################

In [219]:
# נחשב את סטיית התקן של השינוי בווליום - זה מראה כמה הווליום "קופצני"
df['Vol_Instability'] = df.groupby('Name')['Volume_Pct_Change'].rolling(window=10).std().reset_index(level=0, drop=True)
df.tail(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow,Lower_Shadow,Total_Shadow_USD,Shadow_to_Range,Daily_Return,Rolling_Volatility_10D,Volume_Pct_Change,Vol_Instability
589202,2018-01-25,78.47,79.38,78.345,79.25,2327262,ZTS,1.174518,1.174518,0.178731,0.13,0.125,0.255,0.246377,0.011745,0.006500,-9.981875,36.815046
589203,2018-01-26,79.49,80.13,79.380,80.09,2532808,ZTS,1.059937,1.059937,0.302839,0.04,0.110,0.150,0.200000,0.010599,0.006567,8.832095,34.879393
589204,2018-01-29,79.81,79.95,79.110,79.18,2662383,ZTS,-1.136222,1.136222,0.349607,0.14,0.070,0.210,0.250000,-0.011362,0.008626,5.115864,34.776051
589205,2018-01-30,78.44,78.69,77.910,78.35,3808707,ZTS,-1.048245,1.048245,0.934579,0.25,0.440,0.690,0.884615,-0.010482,0.009908,43.056315,35.496621
589206,2018-01-31,78.49,78.77,76.540,76.73,4136360,ZTS,-2.067645,2.067645,0.178685,0.28,0.190,0.470,0.210762,-0.020676,0.011465,8.602736,35.487773
589207,2018-02-01,76.84,78.27,76.690,77.82,2982259,ZTS,1.420566,1.420566,0.143360,0.45,0.150,0.600,0.379747,0.014206,0.012074,-27.901367,37.136987
589208,2018-02-02,77.53,78.12,76.730,76.78,2595187,ZTS,-1.336417,1.336417,0.372655,0.59,0.050,0.640,0.460432,-0.013364,0.012976,-12.979154,24.675051
589209,2018-02-05,76.64,76.92,73.180,73.83,2962031,ZTS,-3.842146,3.842146,0.182339,0.28,0.650,0.930,0.248663,-0.038421,0.017151,14.135552,24.938774
589210,2018-02-06,72.74,74.56,72.130,73.27,4924323,ZTS,-0.758499,0.758499,1.476365,1.29,0.610,1.900,0.781893,-0.007585,0.017031,66.248193,27.230562
589211,2018-02-07,72.70,75.00,72.690,73.86,4534912,ZTS,0.805241,0.805241,0.777945,1.14,0.010,1.150,0.497835,0.008052,0.016890,-7.907909,27.826935

################################### מדד מחיר מול ממוצע נע (Distance from MA) #######################################

In [220]:
df['MA20'] = df.groupby('Name')['close'].transform(lambda x: x.rolling(window=20).mean())
df['Dist_From_MA20'] = ((df['close'] - df['MA20']) / df['MA20']) * 100
df.head(10)

,date,open,high,low,close,volume,Name,Pct_Change,Abs_Pct_Change,gap,Upper_Shadow,Lower_Shadow,Total_Shadow_USD,Shadow_to_Range,Daily_Return,Rolling_Volatility_10D,Volume_Pct_Change,Vol_Instability,MA20,Dist_From_MA20
0,2013-02-08,15.07,15.12,14.63,14.75,8407500,AAL,NaN,NaN,NaN,0.05,0.12,0.17,0.346939,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-02-11,14.89,15.01,14.26,14.46,8882000,AAL,-1.966102,1.966102,0.949153,0.12,0.20,0.32,0.426667,-0.019661,NaN,5.643770,NaN,NaN,NaN
2,2013-02-12,14.45,14.51,14.10,14.27,8126000,AAL,-1.313970,1.313970,0.069156,0.06,0.17,0.23,0.560976,-0.013140,NaN,-8.511596,NaN,NaN,NaN
3,2013-02-13,14.30,14.94,14.25,14.66,10259500,AAL,2.733006,2.733006,0.210231,0.28,0.05,0.33,0.478261,0.027330,NaN,26.255230,NaN,NaN,NaN
4,2013-02-14,14.94,14.96,13.16,13.99,31879900,AAL,-4.570259,4.570259,1.909959,0.02,0.83,0.85,0.472222,-0.045703,NaN,210.735416,NaN,NaN,NaN
5,2013-02-15,13.93,14.61,13.93,14.50,15628000,AAL,3.645461,3.645461,0.428878,0.11,0.00,0.11,0.161765,0.036455,NaN,-50.978516,NaN,NaN,NaN
6,2013-02-19,14.33,14.56,14.08,14.26,11354400,AAL,-1.655172,1.655172,1.172414,0.23,0.18,0.41,0.854167,-0.016552,NaN,-27.345790,NaN,NaN,NaN
7,2013-02-20,14.17,14.26,13.15,13.33,14725200,AAL,-6.521739,6.521739,0.631136,0.09,0.18,0.27,0.243243,-0.065217,NaN,29.687170,NaN,NaN,NaN
8,2013-02-21,13.62,13.95,12.90,13.37,11922100,AAL,0.300075,0.300075,2.175544,0.33,0.47,0.80,0.761905,0.003001,NaN,-19.036074,NaN,NaN,NaN
9,2013-02-22,13.57,13.60,13.21,13.57,6071400,AAL,1.495886,1.495886,1.495886,0.03,0.36,0.39,1.000000,0.014959,NaN,-49.074408,NaN,NaN,NaN

In [221]:
# שמירת הדאטה הנקי לקובץ CSV חדש
# index=True חשוב כאן כי הגדרנו את התאריך כאינדקס ואנחנו רוצים שהוא יישמר בקובץ
df.to_csv('Feature_Engineering_Data.csv', index=True)

print("הקובץ Feature_Engineering_Data.csv נשמר בהצלחה!")

הקובץ Feature_Engineering_Data.csv נשמר בהצלחה!